import streamlit as st

import auth
import database
from ai_engine import generate_resume_review, AIEngineError
from utils import require_auth, page_header, render_chips

require_auth()
user = auth.get_current_user()

page_header("AI TOOLS", "AI Resume Review", "A recruiter-style read on your resume, generated by Gemini.")

analysis = st.session_state.get("current_analysis")
if not analysis:
    st.info("Upload and analyze a resume first.")
    if st.button("Upload a Resume →"):
        st.switch_page("views/upload_resume.py")
    st.stop()

existing_review = analysis.get("ai_review")

if st.button("Generate AI Review", type="primary") or existing_review:
    if not existing_review:
        with st.spinner("Reading your resume like a recruiter would..."):
            try:
                review = generate_resume_review(analysis["raw_text"], role=analysis.get("role"))
                analysis["ai_review"] = review
                st.session_state["current_analysis"] = analysis
                if analysis.get("id"):
                    try:
                        database.update_analysis_ai_review(analysis["id"], user["access_token"], review)
                    except Exception as exc:
                        st.warning(f"Review generated but couldn't be saved: {exc}")
            except AIEngineError as exc:
                st.error(str(exc))
                st.stop()
    else:
        review = existing_review

    st.markdown('<div class="scan-card">', unsafe_allow_html=True)
    st.markdown('<div class="eyebrow">SUMMARY</div>', unsafe_allow_html=True)
    st.write(review.get("summary", ""))
    st.markdown("</div>", unsafe_allow_html=True)

    st.write("")
    c1, c2 = st.columns(2, gap="large")
    with c1:
        st.markdown('<div class="eyebrow">STRENGTHS</div>', unsafe_allow_html=True)
        for s in review.get("strengths", []):
            st.write(f"✅ {s}")
    with c2:
        st.markdown('<div class="eyebrow">WEAKNESSES</div>', unsafe_allow_html=True)
        for w in review.get("weaknesses", []):
            st.write(f"⚠️ {w}")

    st.write("")
    st.markdown('<div class="eyebrow">MISSING SKILLS</div>', unsafe_allow_html=True)
    render_chips(review.get("missing_skills", []), kind="missing")

    st.write("")
    st.markdown('<div class="eyebrow">IMPROVEMENT SUGGESTIONS</div>', unsafe_allow_html=True)
    for s in review.get("improvement_suggestions", []):
        st.write(f"- {s}")

    st.write("")
    st.markdown('<div class="eyebrow">RECRUITER VERDICT</div>', unsafe_allow_html=True)
    st.markdown('<div class="scan-card">', unsafe_allow_html=True)
    st.write(review.get("recruiter_verdict", ""))
    st.markdown("</div>", unsafe_allow_html=True)

    if st.button("Regenerate"):
        analysis["ai_review"] = None
        st.session_state["current_analysis"] = analysis
        st.rerun()
